version: "3.9"

services:
  
  python-api:
    build:
      context: ./python-api
      dockerfile: Dockerfile
    volumes:
      - ./python-api:/app
    ports:
      - 5000:5000
    depends_on:
      - dbBB

  dbBB:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  
  phpmya:
      image: phpmyadmin/phpmyadmin:latest
      container_name: pmafondes
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: dbBB
        PMA_USER: 'user'
        PMA_PASSWORD: password
        UPLOAD_LIMIT: 320M
      ports:
      - 8899:80

volumes:
  my-db:
