get_formation_by_id = "SELECT * FROM formation WHERE id_formation = %(id)s"
get_activite_by_id = "SELECT * FROM activite WHERE id_activite = %(id)s"
get_cp_by_id = "SELECT * FROM cp WHERE id_cp = %(id)s"
get_module_by_id = "SELECT * FROM module WHERE id_module = %(id)s"
get_item_by_id = "SELECT * FROM item WHERE id_item = %(id)s"